### ISSUE TITLE
Updating a site for sitecoordinators returns error 500 (changed title)

### ISSUE THREAD

**Issue by coxthepilot** [Klaital/vitasa-web#86]
As Admin, I added a second site to a Site Coordinator. This was done by updating the SitesCoordinated list on the Site and then Updating the site. Each Site now shows that SC as a SiteCoordinator. When the user is loaded, only one of those sites appears.  Do I need to update the User also. I would expect to be able to update one or the other (I think we previously agreed that the site was the master) and have it reflect in the other (the User).

**Comment by coxthepilot** [comment]
Just noticed that saving the sites coordinated on a site is getting an error 500.

**Comment by coxthepilot** [comment]
The error 500 happens on PUT /sites/mobile-1

**Comment by Klaital** [comment]
There is a known issue where sending a PUT request with only the new Site Coordinator list generates an error. The workaround is to send along another valid field, unmodified, That sounds like the most likely cause of your PUT error.

As for the original error on this issue, I think it's most likely a caching problem. You should be able to manage the Sites <--> Coordinating Users relationship from either end.

**Comment by Klaital** [comment]
Fixed in e88faa19f32cfb648a19bae8e62a11da97eefbc3

**Comment by coxthepilot** [comment]
Update: still getting the 500

PUT /sites/mobile-1

body: 
{"name":"Mobile 1","street":"123 mobi","city":"San Antonio","state":"TX","zip":"78023","latitude":"29.4104978","longitude":"-98.5011676","site_features":["InPersonTaxPrep","Mobile"],"sitecoordinators":[],"contact_name":"","contact_phone":"","notes":"","organization_id":1}

I tried the call with and without the organization_id - no effect. The error occurs with 0 or more entries in the sitecoordinators field. The error seems to occur for all site updates

**Comment by coxthepilot** [comment]
Appears to be tied to sites having Mobile as a site feature.

**Comment by Klaital** [comment]
Nope, just another bug caused by my currently-half-complete notification overhaul. Should be fixed by the same workaround as #93 - I'm effectivly disabling SNS code for now.
